# Generated by Django 3.1.4 on 2020-12-02 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topic',
            new_name='Pizza',
        ),
    ]
